from __future__ import annotations

import importlib


def test_second_stage_modules_import() -> None:
    modules = (
        "src.realtime_pose",
        "src.biomechanics.types",
        "src.biomechanics.landmarks",
        "src.biomechanics.hand_landmarks",
        "src.biomechanics.normalization",
        "src.biomechanics.angles",
        "src.biomechanics.segments",
        "src.biomechanics.velocity",
        "src.biomechanics.stability",
        "src.biomechanics.sequencing",
        "src.biomechanics.session_writer",
        "src.biomechanics.report",
        "src.ui.metrics_overlay",
        "src.utils.time_utils",
        "src.utils.keypoint_schema",
        "src.utils.smoothing",
        "src.utils.angle_utils",
        "src.utils.metrics",
        "src.utils.draw_utils",
        "src.utils.roi",
        "src.utils.device",
        "src.utils.backend_policy",
        "src.backends.base",
        "src.backends.factory",
        "src.backends.mediapipe_backend",
        "src.backends.yolo_pose_backend",
        "src.detectors.yolo_person_detector",
        "src.fusion.yolo_roi_mediapipe",
        "src.realtime.feedback_engine",
        "src.reference.schema",
        "src.reference.library",
        "src.reference.session_loader",
        "src.reference.clipper",
        "src.reference.quality",
        "src.reference.canonicalize",
        "src.reference.features",
        "src.reference.resample",
        "src.reference.dtw",
        "src.reference.compare",
        "src.reference.aggregate",
        "src.reference.report",
        "src.tools.create_reference",
        "src.tools.list_references",
        "src.tools.inspect_session",
        "src.tools.compare_session",
        "src.tools.export_reference",
        "src.fitness.squat.schema",
        "src.fitness.squat.calibration",
        "src.fitness.squat.state_machine",
        "src.fitness.squat.rep_detector",
        "src.fitness.squat.phase_metrics",
        "src.fitness.squat.view_metrics",
        "src.fitness.squat.symmetry",
        "src.fitness.squat.reference_compare",
        "src.fitness.squat.realtime_overlay",
        "src.fitness.squat.report",
        "src.tools.analyze_squat_session",
        "src.tools.calibrate_squat",
        "src.tools.export_squat_report",
        "src.sports.basketball.schema",
        "src.sports.basketball.config",
        "src.sports.basketball.side_selector",
        "src.sports.basketball.shot_clipper",
        "src.sports.basketball.phase_detector",
        "src.sports.basketball.release_proxy",
        "src.sports.basketball.chain_features",
        "src.sports.basketball.sequence_analyzer",
        "src.sports.basketball.arm_alignment",
        "src.sports.basketball.consistency",
        "src.sports.basketball.reference_compare",
        "src.sports.basketball.realtime_overlay",
        "src.sports.basketball.report",
        "src.sports.basketball.ball_tracker_interface",
        "src.tools.analyze_shot_session",
        "src.tools.create_shot_reference",
        "src.tools.compare_shots",
        "src.tools.inspect_shot",
    )
    for module_name in modules:
        importlib.import_module(module_name)
