from __future__ import annotations

import importlib


def test_second_stage_modules_import() -> None:
    modules = (
        "hyrox",
        "hyrox.actions",
        "hyrox.actions.lunge",
        "hyrox.actions.wall_ball",
        "hyrox.config",
        "tools",
        "tools.replay_hyrox_video",
        "src.realtime_pose",
        "src.biomechanics.types",
        "src.biomechanics.landmarks",
        "src.biomechanics.hand_landmarks",
        "src.biomechanics.normalization",
        "src.biomechanics.angles",
        "src.biomechanics.segments",
        "src.biomechanics.velocity",
        "src.biomechanics.stability",
        "src.biomechanics.sequencing",
        "src.biomechanics.session_writer",
        "src.biomechanics.report",
        "src.ui.metrics_overlay",
        "src.utils.time_utils",
        "src.utils.keypoint_schema",
        "src.utils.smoothing",
        "src.utils.angle_utils",
        "src.utils.metrics",
        "src.utils.draw_utils",
        "src.utils.roi",
        "src.utils.device",
        "src.utils.backend_policy",
        "src.backends.base",
        "src.backends.factory",
        "src.backends.mediapipe_backend",
        "src.backends.yolo_pose_backend",
        "src.pose.schema",
        "src.pose.keypoints",
        "src.pose.adapters",
        "src.detectors.yolo_person_detector",
        "src.fusion.yolo_roi_mediapipe",
        "src.realtime.feedback_engine",
        "src.reference.schema",
        "src.reference.library",
        "src.reference.session_loader",
        "src.reference.clipper",
        "src.reference.quality",
        "src.reference.canonicalize",
        "src.reference.features",
        "src.reference.resample",
        "src.reference.dtw",
        "src.reference.compare",
        "src.reference.aggregate",
        "src.reference.report",
        "src.tools.create_reference",
        "src.tools.list_references",
        "src.tools.inspect_session",
        "src.tools.compare_session",
        "src.tools.export_reference",
    )
    for module_name in modules:
        importlib.import_module(module_name)
